### ISSUE TITLE
No texture for Glass [nonvr-companion]

### ISSUE THREAD

**Issue by CuppaCharly** [jrbudda/Vivecraft_114#10]
Glass shows default black and magenta texture.

**Comment by Techjar** [comment]
I thought we disabled connected textures to temp fix this.

**Comment by CuppaCharly** [comment]
Oh, sorry. New to all this and vivecraft.

**Comment by Techjar** [comment]
Yeah just turn off connected textures. I thought it was supposed to be force disabled until we can fix it, but maybe that's not in the release.

**Comment by Techjar** [comment]
You have b0 from GitHub right?

**Comment by CuppaCharly** [comment]
I have no idea. I'm using the non-vr version. Just clicked the installer.

**Comment by CuppaCharly** [comment]
I turned it off now and it's fixed. Any idea on the disarming items when dropped?

**Comment by Techjar** [comment]
Oh, yeah I don't think we disable CTM in non-VR. Just disable it manually for now.

**Comment by CuppaCharly** [comment]
Awesome. Good luck and it's a great mod! Good work :)

**Comment by jrbudda** [comment]
Should be fixed in nonvr-b3.
