### ISSUE TITLE
Noise animations on UI aren't synchronized between eyes

### ISSUE THREAD

**Issue by Brbg** [jrbudda/Vivecraft_114#11]
Some UI such as inventory, crafting tables and offhand item noise animations will diverge between both eyes after a few minutes in game

**Comment by jrbudda** [comment]
im not sure what a noise animation is... can you give me an example or screenshot?

**Comment by Brbg** [comment]
Sorry for the bad description, But the issue seems to have been fixed in a recent release. The best I can describe this animation would be a that the elements would 'wobble' or 'drift' about in space, but I don't see them in the latest release.
