### ISSUE TITLE
Failed to connect to files.minecraftforge.net port 80: Timed out

### ISSUE THREAD

**Issue by Brendan27** [jrbudda/Vivecraft_114#12]
![vivecraft 1 14 3](https://user-images.githubusercontent.com/52599629/60755640-c4625400-a035-11e9-9986-d914df351625.PNG)
Getting this message while trying to boot game...?

**Comment by Brendan27** [comment]
So I copied the URL into a message to a friend and they downloaded the jar file for me, then they sent it back. I had to make a file named 5.2 in the file path along side a file named 5.0.3, then I pasted the missing jar file into the 5.2 file I made and FIXED THIS ISSUE.

**Comment by jrbudda** [comment]
its possible the forge file server was down or something
