### ISSUE TITLE
the game isn't showing in the version list.

### ISSUE THREAD

**Issue by Sh4D0wK1TT3n** [jrbudda/Vivecraft_114#15]
it installs fine but it wont show up on the version list. forge and other stuff dose but this dosent.

**Comment by jrbudda** [comment]
Use task manager to make sure there are no dead instances of MinecraftLauncher.exe running in the background. The 'new' launcher likes to crash out and pin the profiles data in memory, preventing changes made on disk from being read.

**Comment by Sh4D0wK1TT3n** [comment]
Fixed it. Reinstalled minecraft launcher.
Now it's bringing up steam vr loading every other second making it unplayable. Got a gtx 1080ti i7 8700 and 32gb of ram. Why is it lagging so much?

**Comment by jrbudda** [comment]
turn down draw distance, turn off shaders
