### ISSUE TITLE
Game works with no issues up until a world loads, then stops displaying any images in Headset

### ISSUE THREAD

**Issue by AnnEthernetCable** [jrbudda/Vivecraft_114#16]
Pastebin Log: https://pastebin.com/Jv4XVSyB
System info:
    OS = Pop!_OS 18.10 x86_64
    JDK version = 1.8.0_212 (build 1.8.0_212-8u212-b03-0ubuntu1.18.10.1-b03)
    Headset: HTC Vive using SteamVR

The game runs without any issues up until you are dropped in a world, whereas the minecraft application window shows the game running as if it was in the headset; However, the headset 
shows nothing but a blank screen, once in awhile showing the first frame from the application window.

I have checked the FAQ, reinstalled, did a clean install, restarted, and reinstalled java, with no luck.

Any help is appreciated.

**Comment by Techjar** [comment]
This sounds like a SteamVR issue, so I'd try reporting it to them.

**Comment by Pikaro** [comment]
Very similar issue for me: I'm getting a white screen but the game appears to be running. (I can move around etc.)

OS: Fedora 31
Device: Valve Index
Java: OpenJDK 1.8.0_242.

Minecraft: 1.12.2 and 1.14.4 with MultiMC

Behavior is actually slightly different between the two: 1.12 shows an entirely white window on the desktop while 1.14 shows a locked loading screen. 1.14 also shows an error that 1.12 doesn't at the exact moment the world loads:

[15:08:55] [main/ERROR]: Texture submission error: Left/Right AlreadySubmitted:/AlreadySubmitted:

At the same time in the Steam logs:

vrclient_java.txt:Sat Mar 28 2020 15:08:55.637066 - Application submitted two left scene textures for a single frame!
vrclient_java.txt:Sat Mar 28 2020 15:08:55.637114 - Application submitted two right scene textures for a single frame!

The logs for 1.12 are entirely uninteresting as far as I can tell.

1.12.2: https://paste.ee/p/NT5m0
1.14.4: https://paste.ee/p/eE5fl

**Comment by Pikaro** [comment]
... as always, 30s after posting an issue report I randomly find the fix. Enable internal shaders. (Or probably others.)

**Comment by Pikaro** [comment]
OK, got 1.12 working by simply switching to internal shaders.

1.14 is still broken, but now in a different way: The mirror window shows the world, the VR headset is being tracked. In the headset, I only see a static (but very juddery) half-frame. The same error is still being logged. So it looks like these were independent phenomena. And from the error message, I don't think the issue is on SteamVR's side.
