### ISSUE TITLE
Custom Item Rendering for Misc Items

### ISSUE THREAD

**Issue by NPC-8606** [jrbudda/Vivecraft_114#18]
Basically a suggestion to implement custom rendering for miscellaneous items so that they render similar to how swords do now. (List at bottom)

Vanilla minecraft sort-of implements as i'll show in some screenshots down below

https://media.discordapp.net/attachments/178567952780623872/600270913509785600/2019-07-15_11.21.26.png?width=700&height=394

https://media.discordapp.net/attachments/178567952780623872/600270927066038282/2019-07-15_11.21.23.png?width=700&height=394

https://media.discordapp.net/attachments/178567952780623872/600270904546820114/2019-07-15_11.21.20.png?width=700&height=394

List of items for custom rendering (From my testing these are the items that also render differently on vanilla minecraft):

Bone Item
Blaze Rod
Stick
Bamboo item

**Comment by firestorm185** [comment]
Are you talking about custom angles and item offsets? I just posted a bug report for that over on the forums, but I'm not sure if that what you mean.

**Comment by jrbudda** [comment]
hey we did this one.
