### ISSUE TITLE
Non VR cannot see VR Player Models

### ISSUE THREAD

**Issue by NiteKat** [jrbudda/Vivecraft_114#2]
I downloaded and ran the VR installer. Girlfriend downloaded and ran the non-VR installer. I opened a new world, opened to LAN, and she joined. She was unable to see my player model, could only see a shadow where I was standing and moving.

**Comment by jrbudda** [comment]
ah ya know I didn't test LAN

**Comment by SquidHater1** [comment]
After some testing, non VR players can't see the VR player's model even on a server with the spigot plugin installed

**Comment by jrbudda** [comment]
this should be fixed
