### ISSUE TITLE
No focus on ingame menus

### ISSUE THREAD

**Issue by galadril** [jrbudda/Vivecraft_114#21]
I've an issue with my Oculus Rift S, that when I put the headset a way for like 1minute (a break) and put it back on, all the menu's in game are not working anymore.

So i can toggle the menu's, but i cant select an item because there the crosshair doesn't has any focus on the dialogs...

This also happens some times when just starting vivecraft, the first menu then doesn't show my crosshair..

any thoughts?

**Comment by ZwipZwapZapony** [comment]
If you have Vivecraft's game window set to run in fullscreen on the desktop display, can you confirm whether or not the Vivecraft window was actively selected on your desktop?
(Minecraft: Java Edition uses exclusive fullscreen mode. This means that if Minecraft isn't in focus, it gets minimized. And as Vivecraft tells Minecraft "the player has the cursor here" for GUI stuff and Minecraft's window becomes 0x0 pixels when minimized, Vivecraft doesn't seem to work right if it's minimized.)

**Comment by galadril** [comment]
I think that Vivecraft had fullscreen and was visible/active when it happened, but ill try and check a couple of nights. Thanks, ill report back
