### ISSUE TITLE
Some controller inputs don't work

### ISSUE THREAD

**Issue by Kyledude252** [jrbudda/Vivecraft_114#22]
I can't get the rotate left and rotate right actions to work, along with swiping left/right on the vive trackpad to swipe left/right through the hotbar. I have rotate left/right assigned to clicking the left/right of the left trackpad, but it isn't working. I got free rotate to work, but that makes me too motion sick. I see there was also an option for swiping the trackpad to rotate, but couldn't get that to work either, plus I would prefer to use button presses instead of swiping. For hotbar swiping there were a few options, but either the swiping was sporadic, or vertical with a ton of inertia, and constant scrolling if I held the top or bottom. I hope these issues can be fixed, mostly the rotate option as that's something I need in a VR game to be able to enjoy.

**Comment by mjdixon** [comment]
I have this issue as well.

**Replication:**
On a controller trackpad settings
Create DPAD
Set East -> Rotate Right
Set West -> Rotate Left
Save

Clicking the assigned trackpad results in no actions.

**Note:**
Removing one of the 'Rotates' from the bindings, will allow the other to work as expected.

**Comment by Techjar** [comment]
Yeah this is a SteamVR bug.

**Comment by Techjar** [comment]
Yeah, the rotate thing is a SteamVR bug. As for the hotbar, those worked fine in my testing and you likely just configured it wrong.
