### ISSUE TITLE
Left-handed controls, haptics on the right hand.

### ISSUE THREAD

**Issue by pooky9123** [jrbudda/Vivecraft_114#23]
I've done a left-handed layout (and remapped my controls so it works well in a left-handed layout), but when I for example mine with my pickaxe in my left hand, I feel the haptics in my right hand.

The haptics worked correctly before the SteamVR controls update.

**Comment by jrbudda** [comment]
is this with the current (r4) version?

**Comment by pooky9123** [comment]
Actually, I was with r3, but I've installed r4 and checked again... Same issue. I ensured the "Reverse hands" option is enabled.

Also, forgot to mention that I am on HTC Vive.

**Comment by jrbudda** [comment]
OK, it's supposed to be reversing the haptics but I will check it out.

**Comment by Techjar** [comment]
I can't reproduce this. How exactly are you using the pickaxe?

**Comment by jrbudda** [comment]
It's been fixed in dev it's just not in the release

**Comment by Techjar** [comment]
Yeah, just needs to be updated. My bad.

**Comment by jrbudda** [comment]
this should be in the 1.14.4 release

**Comment by pooky9123** [comment]
Just checked the latest release (1.14.4v2). Haptics now work properly in the left hand. 😃
