### ISSUE TITLE
Swimming Under Blocks

### ISSUE THREAD

**Issue by d-goods** [jrbudda/Vivecraft_114#26]
When swimming underneath blocks, if you swim upward, your head will clip into the blocks. 

I'm assuming this happens because I'm standing in VR space so my players box is still two blocks high rather than the one block it should be while swimming.

**Comment by jrbudda** [comment]
Yea, I'll never understand why they made your hitbox and camera drop down to your knees instead of just bringing the hitbox up and leaving the camera alone.

**Comment by d-goods** [comment]
Oh dang. Not fixable then?

**Comment by jrbudda** [comment]
There's probably something really gross I could do by temporarily offsetting your VR room floor, but it would be real hacky and unknown what kind of motion sickness it might induce.

**Comment by jrbudda** [comment]
I think i did this.
