### ISSUE TITLE
Some settings reset on game reboot.

### ISSUE THREAD

**Issue by pooky9123** [jrbudda/Vivecraft_114#27]
I've noticed that when I change some settings like "auto sprint threshold" to 1.0 and "enable autosprint" to OFF (both in the free move section), they reset to their default values after I exit and come back to the game. The "swap hands" and "disable backback switch gesture"  seems to retain.

Version: 1.14.4 v2 r2

**Comment by jrbudda** [comment]
It appears the code is missing to save/load those 2 settings, which are new. Will fix. Thank you for the report.

**Comment by Techjar** [comment]
Fuck dammit

**Comment by jrbudda** [comment]
that's techjarese for 'thank you for the report, this will be fixed promptly.'
