### ISSUE TITLE
Java 8 is EOL. Use JDK 11 and bundle the slimmer runtime.

### ISSUE THREAD

**Issue by andrewsf** [jrbudda/Vivecraft_114#28]
JDK 8 is long end-of-life.
Upgrade to use JDK 11.
Use jlink, etc. to bundle the runtime so that your users don't have to download/install Java 8.

**Comment by Techjar** [comment]
Minecraft uses Java 8, therefore we use Java 8. Go bug Mojang about this, not us.

**Comment by Techjar** [comment]
Also, if you're referring to the installer, chances are it will work fine when run under Java 11. We don't want to bundle a runtime with the installer as it will massively increase the file size.
