### ISSUE TITLE
Issue with lens distortion on index?

### ISSUE THREAD

**Issue by ragesaq** [jrbudda/Vivecraft_114#29]
I use obs openvr plugin for both left eye and right eye for a blended FPV that looks more natural. This works great in other openVR games but there appears to be an issue with the way the lens distortion for the eye is handled in Vivecraft 1.14.4 v2, the shape is different which makes this blending technique not work correctly.
Please see this video for a video demonstrating the lens distortion differences between other openvr games and Vivecraft. This discrepancy causes visual artifacts as the blending is no longer accurate. 
https://www.twitch.tv/videos/462794629

**Comment by Techjar** [comment]
By "lens distortion" are you referring to the eye stencil/hidden area mesh? That's provided to us by the API, along with everything else, so it's impossible for it to be wrong. What's probably happening is the hidden area mesh for Index is a bit smaller than what the OBS plugin is expecting, but whatever other games you're trying aren't using the mesh from the API.

**Comment by ragesaq** [comment]
That is correct, and that is the part that appears to be the problem. My video shows it plain as day so I'm not sure what is going on.
In my video I switch between two games without changing anything else. I tested multiple games and they all had the same stencil, Vivecraft was significantly different. 
Stand Out (Unity, not updated for index, but new enough to work fine with Index + Knuckles)
Contractors (Unreal, updated for Index)
Blade & Sorcery (Unity, updated for Index)
Beat Saber (Unity, updated for Index)

**Comment by Techjar** [comment]
If it's an issue, just turn the stencil off in the stereo rendering options. Like I said it can't be wrong as we pull it from the API.

**Comment by Techjar** [comment]
Turns out the stencil is upsidedown. Someone forgot about OpenGL's inverted Y coordinate space again.
