### ISSUE TITLE
VR players are tiny when (re)connecting to a multiplayer server

### ISSUE THREAD

**Issue by Entity447B** [jrbudda/Vivecraft_114#30]
I've been playing on a server of mixed VR and screen players. When a VR player connects to the server, their avatar appears comically small until they use the "calibrate height" option, at which point they return to normal size.

**Comment by Techjar** [comment]
As in the height is small every time they reconnect?

**Comment by Entity447B** [comment]
Yeah.

**Comment by jrbudda** [comment]
I think this was fixed in the plugin.
