### ISSUE TITLE
Pause menu UI is clipped

### ISSUE THREAD

**Issue by Brbg** [jrbudda/Vivecraft_114#33]
The pause menu is too large for what it's being rendered on and is clipped outside of it. The option to change the UI scale also doesnt work. 

![Screenshot](https://user-images.githubusercontent.com/52596359/62817684-2c98de00-bb7e-11e9-8676-63a49ea338f1.PNG)

This also stops players from quitting the game. I'm stuck in minecraft. Please send help.

**Comment by Techjar** [comment]
Make your game window bigger. The GUI is necessarily tied to the window size.
