### ISSUE TITLE
Colors pulsing between normal colors and orange tint

### ISSUE THREAD

**Issue by Octavian-the-ent** [jrbudda/Vivecraft_114#34]
I have resource packs and shaders turned off, issue is not present when playing flat 1.14 or in other VR games. I have f.lux on desktop disabled.
Pulsing happens about once a second. Very annoying. 
pls help jrbudda-san

**Comment by Espergium** [comment]
You should heal yourself.

**Comment by Octavian-the-ent** [comment]
For real? its just a low health indicator?

**Comment by jrbudda** [comment]
yee ❤️ ❤️ ❤️ 💔 💔
