### ISSUE TITLE
Render Setup Failed

### ISSUE THREAD

**Issue by IronFootBoy1234** [jrbudda/Vivecraft_114#35]
I've been having all kinds of troubles setting this up but I'm trying to use my Oculus Quest but the game just keeps giving me error messages. They all say "Render Setup Failed" and then "HMD detected over USB, but Monitor not found (208)" and "Driver Failed (200)"
Most of the time my game crashes right after the Mojang loading screen right before the buttons pop up.
[hs_err_pid18488.log](https://github.com/jrbudda/Vivecraft_114/files/3498084/hs_err_pid18488.log)
[hs_err_pid15064.log](https://github.com/jrbudda/Vivecraft_114/files/3498085/hs_err_pid15064.log)

**Comment by Dasonic** [comment]
Is steam vr loading? I fixed this issue by launching steam vr first, then launching vivecraft.

(This is on linux using streamvr beta 1.7.12 with the vive)
