### ISSUE TITLE
Rift S crash and lose connection upon getting past start menu

### ISSUE THREAD

**Issue by joannawolthuis** [jrbudda/Vivecraft_114#36]
Hi there! I recently got an oculus rift S and am excited to play Minecraft with Vivecraft on it.
I've not had much problems with the rift in general (although I see a LOT of bugs on it) but I have serious issues running Vivecraft, this is what happens now:

1. start computer
2. start oculus app
3. start minecraft and enter vivecraft profile
4. get to main menu just fine, arms move etc
5. on joining game, i lose connection, one of two ways:
a. i can see everything moving, but i cannot move as the connection with the headset is gone
b. black screen
6. upon removing headset, in Oculus i get an extra right touch controller for some reason?? and the rest is disconnected. Need to remove the extra touch controller through editing some files in the oculus folder.

either way, steamVR tells me the headset has disconnected, and I need to restart my PC and replug my Rift to get it back to normal again,

I've managed to get in and play 3 times out of 20 attempts now, if in it works fine. I'm not sure if this is steamVR because the other games I've tried through Steam work fine... 
I've attached my log file, I hope it's useful :) 
[latest.log](https://github.com/jrbudda/Vivecraft_114/files/3562878/latest.log)

**Comment by Techjar** [comment]
Unfortunately whatever is going on here is out of our control. You'll need to bug Valve/Oculus about this one.

**Comment by joannawolthuis** [comment]
that's ok, thank you :) ill go see if they know anything!

**Comment by Techjar** [comment]
It's really odd considering that there's nothing different in how we interact with the OpenVR API while in-world vs on the main menu. Perhaps your system is running out of resources or something?

**Comment by joannawolthuis** [comment]
Maybe, I wouldn't be surprised honestly! Next week I'm getting a beefier setup, that may solve the problem, its just so weird that it's only minecraft (although it can be resource heavy I guess, haha!)
