### ISSUE TITLE
Disembodied arms with Rift S

### ISSUE THREAD

**Issue by joannawolthuis** [jrbudda/Vivecraft_114#37]
Disabled some power settings and could get in now, haha!
If others look at my character ingame or I look at my inventory screen, my character has disembodied arms kind of in front and above me, others with the Rift older versions don't seem to have this problem, is it some kind of tracking adjustment/calibration?

I'll attach a screenshot in a bit ^^

**Comment by Techjar** [comment]
I'm not sure what you mean, arms being detached visually is just normal. Are they floating father away than usual? A screenshot would help.

**Comment by joannawolthuis** [comment]
it looks like my arms are high up in the air in front of me and more so than the other VR players,  gimme a sec I'll attempt a screenshot :)

**Comment by Techjar** [comment]
Make sure you calibrate your height.

**Comment by joannawolthuis** [comment]
Calibrating height and restarting made it more normal, thanks :) still a bit wacky in terms of arms being slightly off (like arms by side in real life is sticking arms into minecraft body, etc), but I can imagine that's more expected behaviour?

**Comment by Techjar** [comment]
Yeah, your character is way bigger than an actual human, so it's going to be a bit janky no matter what.

**Comment by joannawolthuis** [comment]
alright :D thanks so much for your super fast replies!
