### ISSUE TITLE
The steamvr input doesn't work with the oculus quest.

### ISSUE THREAD

**Issue by HCShelton** [jrbudda/Vivecraft_114#38]
I used to be able to play just fine with riftcat connected to my quest, but when it all of a sudden required steamvr input the controllers are unresponsive, and it's only with vivecraft every other game works. So until this is fixed I will not use or recommend vivecraft to anyone.

**Comment by Techjar** [comment]
This is an issue with Vridge, they need to support SteamVR Input.

**Comment by HCShelton** [comment]
ok thanks

**Comment by HCShelton** [comment]
you should still be able to use it with or without steamvr input though.

**Comment by Techjar** [comment]
We can't support both SteamVR Input and the legacy input API, they are fundamentally very different. We chose to switch to SteamVR Input as it provides proper support for the new Index controllers, and makes less work for us while providing more features in regards to rebinding controls.

If you need a version that still supports legacy input, you can use 1.13.2 v2 or 1.12.2 v8. Sorry but this is the way forward, and if drivers don't update to support it then that's on them.

**Comment by HCShelton** [comment]
OK thanks for the feedback.
