### ISSUE TITLE
installer not opening

### ISSUE THREAD

**Issue by kostvi** [jrbudda/Vivecraft_114#39]
whenever i try to open the installer it refuses to open. i have tried to run it in admin mode. i havent been able to find a solution and i havent been able to get more information about the problem.

**Comment by TheTrueForce** [comment]
Have you got Java installed? The one Minecraft uses doesn't count; it's not available to the rest of the system.

**Comment by kostvi** [comment]
the newest version of of java is installed

**Comment by Techjar** [comment]
Open up cmd/powershell and run the installer like so: `java -jar file-name-of-installer.exe`

**Comment by Techjar** [comment]
Open up cmd/powershell and run the installer like so: `java -jar file-name-of-installer.exe >installer.log`

Then upload the resulting installer.log file.

**Comment by kostvi** [comment]
it is unable to access it

**Comment by Techjar** [comment]
Something (perhaps anti-malware) is blocking it then.

**Comment by kostvi** [comment]
all anti-malware  is off and there is no different result.

**Comment by Techjar** [comment]
Double check your anti-malware hasn't already quarantined the file despite being disabled. Some anti-malware is particularly nasty about stuff like that (I'm looking at you, Panda).

**Comment by kostvi** [comment]
i have dubble cheked and the anti-malware has not quarantined anything.

**Comment by Techjar** [comment]
Well, I dunno what to tell you. Something is surreptitiously blocking the file, so you'll have to figure out what that is and stop it.

**Comment by TheTrueForce** [comment]
Was the command-line in the right directory? If you just opened cmd/PS from the start menu and ran the command, it's highly unlikely to work, because it starts in some default directory that is almost never what you want.

**Comment by kostvi** [comment]
i started it by typing cmd in the windows + r tab.

**Comment by TheTrueForce** [comment]
You need to get it into the same directory as the installer file, or it won't work for obvious reasons. use the cd command, or shift-right-click to get one straight in the directory.

**Comment by TheDunkShot** [comment]
Same thing is happening to me. Seems to be a windows issue, the java control panel refuses to load either. I've re-installed java many times and I'll probably need to reset my pc.

**Comment by TheTrueForce** [comment]
What does it tell you if you open up cmd or powershell and run the command `java -version`?

**Comment by TheDunkShot** [comment]
I fixed this issue, RivaTuner has its own Java install, if you have rivatuner it may mess with your java.
