### ISSUE TITLE
Game crashes before loading

### ISSUE THREAD

**Issue by fuzzhead206** [jrbudda/Vivecraft_114#4]
I've installed everything correctly, had steamVR open or closed, doesnt matter, the second I click play on the launcher it gives some generic error.  Dont even get a minecraft window before it crashes.

**Comment by Espergium** [comment]
Pastebin the log from .minecraft/logs

**Comment by fuzzhead206** [comment]
Unfortunately I'm not at home right now but I will do as soon as I get home

**Comment by fuzzhead206** [comment]
https://pastebin.com/QUEHGnmC

**Comment by fuzzhead206** [comment]
> Unfortunately I'm not at home right now but I will do as soon as I get hom

**Comment by jrbudda** [comment]
did you resolve this? was as out-of-memory error

**Comment by fuzzhead206** [comment]
I have not gotten it to work, I've allocated it up to 12 gigs of ram and it
hasn't done anything but crash on launch, sadly.

**Comment by Techjar** [comment]
It's a GL out of memory error, which means the driver is running out of memory. You should try allocating *less* RAM to the game, and perhaps reboot if you haven't.

**Comment by fuzzhead206** [comment]
Even running with 1 or 2 gigs of ram doesn't work.  But at least the game
went from not opening a Minecraft window at all to opening one for a
quarter second before crashing...

**Comment by 203Null** [comment]
I reset the JVM arg in the launcher and it works
