### ISSUE TITLE
Optifine F2 doesn't support SEUS PTGI

### ISSUE THREAD

**Issue by TechnoStone** [jrbudda/Vivecraft_114#42]
Please update Optifine for at least F3 to be able use RayTracing in SEUS PTGI

**Comment by groenkek** [comment]
@TechnoStone is this fixed by the latest release?

**Comment by gavinc** [comment]
I just ran this last night (for the first time, just discovered this) seus ptgi does indeed work. obv, slow depending on hware (gtx1080, ryzen7 1800x, 16gb).

**Comment by TechnoStone** [comment]
> @TechnoStone is this fixed by the latest release? (Since its updated to F4)

I'll check this as soon as I can

**Comment by TechnoStone** [comment]
So, now it works fine on my i7-7700K + Radeon VII
