### ISSUE TITLE
Can't download install file

### ISSUE THREAD

**Issue by YazTDB** [jrbudda/Vivecraft_114#43]
I'm new to vivecraft and just heard about it. When I click the link on the vivecraft page (http://www.vivecraft.org/downloads/) that says Vivecraft 1.14.4 and click on the vivecraft-1.14.4-jrbudda-3-r1-installer.exe, it just takes me to an error page 'This site can’t be reachedgithub-production-release-asset-2e65be.s3.amazonaws.com’s server IP address could not be found.
Try running Windows Network Diagnostics' I've had the same result on all versions, and two different peoples computers.

**Comment by jrbudda** [comment]
This is clearly an issue with your computer or internet service. There are no reported outages at github and the file downloads fine for me.

**Comment by YazTDB** [comment]
OK Thank you :D

**Comment by Techjar** [comment]
Try changing your DNS servers to Google DNS, the DNS servers provided by ISPs are often terrible.

**Comment by YazTDB** [comment]
It seems to be working now, but that you for the responses!
