### ISSUE TITLE
My hands don't move (quest), (VD)

### ISSUE THREAD

**Issue by ChubbyCats22** [jrbudda/Vivecraft_114#45]
I can join the menu just fine but I can't move my hands. if I wanted to click anything I would need to use my mouse. I have looked everywhere. I can move my head but my hands just follow where ever my head goes.

**Comment by Techjar** [comment]
Make sure it's in standing mode.

**Comment by ChubbyCats22** [comment]
> Make sure it's in standing mode.

Ok I will try

**Comment by ChubbyCats22** [comment]
Nope didn't work

**Comment by ChubbyCats22** [comment]
My controllers are being tracked but they don't control in VR, when I am in desktop mode they sort-of work but not really.

**Comment by Techjar** [comment]
Please upload the `latest.log` from `.minecraft/logs` (and make sure it's a Vivecraft log, not vanilla), that'll tell us more about what's going on.

**Comment by ChubbyCats22** [comment]
[latest.log](https://github.com/jrbudda/Vivecraft_114/files/3774878/latest.log)

**Comment by ChubbyCats22** [comment]
> Please upload the `latest.log` from `.minecraft/logs` (and make sure it's a Vivecraft log, not vanilla), that'll tell us more about what's going on.

[latest.log](https://github.com/jrbudda/Vivecraft_114/files/3774936/latest.log)

**Comment by Techjar** [comment]
`Something's taking too long! 'root.Poll.updatePose' took aprox 100.2103 ms`

This looks suspicious. Perhaps there's something wrong with SteamVR or Virtual Desktop, although "hands following head" really sounds like it's in seated mode (in Vivecraft settings, not SteamVR or whatever).

**Comment by ChubbyCats22** [comment]
So "standing/sitting" modes are in vivecraft settings? I thought you meant quest settings. Correct me if I am wrong.

**Comment by ChubbyCats22** [comment]
Nevermind I found it. It works! Thanks so much!

**Comment by Techjar** [comment]
You may want to turn shaders off as it appears to be making your framerate horrendous.
