### ISSUE TITLE
Too short in Vivecraft 

### ISSUE THREAD

**Issue by MrFluffls** [jrbudda/Vivecraft_114#49]
I recently downloaded Vivecraft and I am only 1 block tall, I tried reinstalling it but im still only 1 black tall, I also tried to recalibrate my hight in game but it says that im appearantly only 1.65m tall when in reality im 1.87m tall, It also didn't adjust my hight what so ever, are there any fixes to this problem ?

**Comment by Techjar** [comment]
Stand up?

**Comment by MrFluffls** [comment]
I am

**Comment by Techjar** [comment]
Sounds like maybe your VR system is miscalibrated, putting you slightly in the floor.

**Comment by MrFluffls** [comment]
could be just for this game I guess, because in any other vr title I am my correct Hight

**Comment by Techjar** [comment]
Are you playing in standing or seated mode (in vivecraft settings)?

**Comment by MrFluffls** [comment]
standing mode

**Comment by Techjar** [comment]
Did you by chance accidentally enable standing origin offset?
