### ISSUE TITLE
This application requires a Java Runtime Environment 1.8.0

### ISSUE THREAD

**Issue by creepinson** [jrbudda/Vivecraft_114#50]
Hello. I am using the 1.14.4 VR client and I HAVE installed AdoptOpenJDK 1.8.0_232 and it still says I need a JRE when I run the installer. Then it brings to me to Oracle JRE!
I have added the JDK to my path and verified javaw and java -version is working in command prompt.

**Comment by Techjar** [comment]
Dunno, I guess launch4j doesn't like OpenJDK. Run it manually with `java -jar path-to-installer-exe`
