### ISSUE TITLE
Two Things

### ISSUE THREAD

**Issue by jjkosek4** [jrbudda/Vivecraft_114#51]
Hello I have downloaded Vivecraft its a amazing game but just a few problems. First thing is there is no mobs spawning in the map in any gamemode and personally I think they are the fun and challenging part of the game. The second thing is the map its not infinite and has a limited amount of space. Anyway it would be so nice if I had answers on this to go back to playing my favorite game. THANK YOU!!!

**Comment by Espergium** [comment]
Vivecraft doesn't modify either of these

**Comment by InsaneGrox** [comment]
on my install, mobs should spawn like crazy (dare I say it it's a bit excessive), and the world being infinite, well, I can go out to 30 billion blocks on either X or Z before running into the worldborder, exactly the same as vanilla, either you launched the bedrock edition on accident, or you should re-install vivecraft, and elaborate.

**Comment by firestorm185** [comment]
Yeah, that sounds like either you're playing a very old minecraft map or your computer is just glitched because Ive been playing Vivecraft for ages and haven't had any of those problems. Also what version of Vivecraft are you using?

**Comment by Espergium** [comment]
1. Vivecraft doesn't modify the issues explained in the first post.
2. The issue thread was hijacked.
3. This isn't a vivecraft problem.
