### ISSUE TITLE
Vivecraft uses wrong GPU

### ISSUE THREAD

**Issue by burdoto** [jrbudda/Vivecraft_114#53]
Consider this scenario:
- Using VR on a Laptop with an Intel integrated GPU AND an NVidia GTX 1060M
- Said laptop is proven to be working fine with Steam store VR apps, Oculus Store Apps
- As soon as Vivecraft is used, SteamVR shows a popup that my VR headset is plugged into the wrong GPU (which it obviously is not the case, e.g. BeatSaber is proven to run in the exact same SteamVR instance)

This leads to the conclusion that Vivecraft might be trying to use the Intel integrated GPU instead of the correct GPU, the GTX060.

**Comment by Espergium** [comment]
This is the most common issue which is covered in the faq.

**Comment by burdoto** [comment]
The fix covered in FAQ did not help.

**Comment by Techjar** [comment]
Yeah you need to set the preferred GPU in the NVIDIA Control Panel (global tab, per-application won't work). We can't provide the Optimus hint ourselves for technical and licensing reasons.

**Comment by burdoto** [comment]
Again, that is what I already tried but still didn't help.

**Comment by Techjar** [comment]
Your laptop might not be compatible with VR. Some have the HDMI port connected to the integrated instead of dedicated GPU.

**Comment by burdoto** [comment]
Did you read? BeatSaber runs perfectly fine without even restarting SteamVR in between...

**Comment by Techjar** [comment]
Perhaps you aren't setting the preferred GPU correctly then? I dunno. It's worked for everyone else.

**Comment by burdoto** [comment]
Could you elaborate what you mean by NVCP?
Also, the related log file can be found here: http://kaleidox.de/cdn/github.com/jrbudda/Vivecraft_114/issue-53/vivecraft-1.log

**Comment by burdoto** [comment]
I had noticed that the NVidia settings for some reason kept changing the global setting to the integrated graphics unit, possibly due to a permission problem. Both problems are now fixed.

**Comment by Techjar** [comment]
Huh, never seen that happen before. Mind elaborating on how you fixed it in case the same thing happens to others in the future?

**Comment by burdoto** [comment]
Basically, _someone_ (I know who, but this is another book) changed access permissions of multiple directories which seems to have caused NVidia to not store changes properly. That, or it was caused by a Trojan that said _someone_ has brought onto this PC.
