### ISSUE TITLE
GUI's are too far out.

### ISSUE THREAD

**Issue by DaikiChen** [jrbudda/Vivecraft_114#54]
So I just started playing Vivecraft (Rift S, 1.14 latest version) with my friends (Non-VR) and I have noticed that the GUI menus are WAYYYY too far out and it makes doing things like chest management or smelting very very difficult. If you could add a setting to add fixed location GUI's that would be good. (Note: The main menu, Pause menu and inventory are all fixed location it's just block GUI  ones)

![Capture](https://user-images.githubusercontent.com/57613022/71650497-6d320780-2d6a-11ea-96de-b7d6436534b9.PNG)
![Capture](https://user-images.githubusercontent.com/57613022/71650522-90f54d80-2d6a-11ea-93b6-8dff732bfc2b.PNG)

Edit 1: Also, if possible, could you make the GUIs slightly larger after they've been put in fixed locations, to the point where they start to curve around your head, like say Oculus GUIs.

**Comment by jrbudda** [comment]
this is now an option in 1.15
