### ISSUE TITLE
SteamVR won't track my controllers with my Oculus quest while using Virtual Desktop, Please Help?!?

### ISSUE THREAD

**Issue by DevRGB** [jrbudda/Vivecraft_114#55]
SteamVR wont track my quest controllers while using Virtual Desktop anyone got a fix?

**Comment by Espergium** [comment]
Use ALVR.
http://www.vivecraft.org/vivecraft-for-mobile-vr/

**Comment by DevRGB** [comment]
ALVR doesnt work for me it has connection errors.

**Comment by DevRGB** [comment]
I got it fixed, thanks for the seated mode thing.

**Comment by StackDoubleFlow** [comment]
I'm not sure if you know about this, but I have found [this fork of ALVR](https://github.com/JackD83/ALVR/releases) to be  generally better and more up to date.

Also, if everything is fixed it may be a good idea to close this issue.
