### ISSUE TITLE
Custom Model Offset implimentation

### ISSUE THREAD

**Issue by firestorm185** [jrbudda/Vivecraft_114#58]
I just finished making my first ever custom 3D model pack for Minecraft, but unfortunately it doesn't work in Vivecraft due to Vivecraft not taking into account custom model offsets. Would be awesome if that could be implimented so I could use all the amazing 3D models people have created!

Here's a few examples of what I mean:

![2020-02-21_14 54 40](https://user-images.githubusercontent.com/12396056/75073031-a6fbd080-54c6-11ea-8261-fea15e49cabc.png)
https://imgur.com/a/PZidGCX

![OculusScreenshot1582279942](https://user-images.githubusercontent.com/12396056/75073011-9c413b80-54c6-11ea-848a-f4fc84383db3.jpeg)
https://imgur.com/a/MqVoMlE

**Comment by jrbudda** [comment]
Model offsets for 1st person view are calculated from the camera location. They do not just magically 'work' in VR unless you want your item rendered a half meter down and to the left of the hand.

**Comment by jrbudda** [comment]
hey we did this.
