### ISSUE TITLE
not much of a bug I just need some tips on what to do

### ISSUE THREAD

**Issue by newvivecraftuserwhocantplay** [jrbudda/Vivecraft_114#60]
I wanted to play vivecraft for the first time (im using nvidia laptop) but it said i was using preferred gpu so i followed the directions that were supposed to help me fix it but the gpu changing is now in windows settings, i go there i have to choose which app i want to change my gpu settings on thats where im stuck please send feedback

**Comment by Espergium** [comment]
Use the nvidia control panel as shown in the guide. If you do not have it then go to nvidia and install a driver update (preferably) without geforce experience.

**Comment by newvivecraftuserwhocantplay** [comment]
i have control panel and i went to the area i was supposed to change but it said windows now handles the preferred gpu
ill send screenshot in a sec

**Comment by newvivecraftuserwhocantplay** [comment]
![screenie](https://user-images.githubusercontent.com/87439744/125660303-ebe38dcd-7128-4fb0-9157-f505c304f3a2.png)

**Comment by MeowMC** [comment]
So hit the blue text and change it there, not that hard

**Comment by newvivecraftuserwhocantplay** [comment]
hold on lemme restart my computer im trying something

**Comment by newvivecraftuserwhocantplay** [comment]
ok im back

**Comment by newvivecraftuserwhocantplay** [comment]
i didnt work

**Comment by newvivecraftuserwhocantplay** [comment]
> So hit the blue text and change it there, not that hard

it says i have to browse which files i want it to affect

**Comment by Espergium** [comment]
Set preferred adapter to the nvidia GPU via the control panel. Ignore the notice. The nvidia control panel will still work.

Also no need to spam the replies. Use the edit button.

**Comment by newvivecraftuserwhocantplay** [comment]
i cant click on the option i have to use the windows graphics settings

**Comment by newvivecraftuserwhocantplay** [comment]
ok imma close i just figured it out
