### ISSUE TITLE
Can't download Optifine during install

### ISSUE THREAD

**Issue by onianimegod** [jrbudda/Vivecraft_114#8]
![image](https://user-images.githubusercontent.com/47126198/60747929-dd480800-9f56-11e9-8be6-50402f80b15b.png) i get this error every time i try to install 1.14.3 is there a reason this is happening?

**Comment by jrbudda** [comment]
check firewall, antivirus, or anything else that may be preventing the installer from accessing the internet.

**Comment by onianimegod** [comment]
> check firewall, antivirus, or anything else that may be preventing the installer from accessing the internet.

problem solved, had to run as administrator. also love what you do man keep it up!

**Comment by Techjar** [comment]
Fix the permissions on your minecraft directory.
