### ISSUE TITLE
Items disappear when thrown

### ISSUE THREAD

**Issue by Connor-Knabe** [jrbudda/Vivecraft_114#9]
v.1.14.3
Operating system: macOS 10.14.5

On the non-vr client (either hosting or not hosting a LAN server) when you drop an item it disappears.  

Expected behavior
1. hit Q to drop item
2. item is able to be picked up and appears on the ground

Actual behavior
1. hit Q to drop item
2. item disappears from inventory and is nowhere to be found.

Thanks for all that you've done with this mod. It's great!

**Comment by jrbudda** [comment]
should be fixed now

**Comment by Connor-Knabe** [comment]
Great thanks @jrbudda! Such a quick response! Any idea when that'll get committed? Appreciate everything that you've done with this project. Thank you again!
